apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  labels:
    app: microservicio
    areanegocio: pagos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: hola-mundo
          image: chris100500/hola-mundo:5
          ports:
            - containerPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: microservicio
spec:
  selector:
    app: microservicio
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
